name:                ghidra-lifter
version:             0.1.0.0
github:              "theKidOfArcrania/ghidra-lifter"
license:             BSD3
author:              "theKidOfArcrania"
# maintainer:          "example@example.com"
copyright:           "2021 theKidOfArcrania"

extra-source-files:
- README.md
- ChangeLog.md

ghc-options:
- -g
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -fno-warn-orphans

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- text
- transformers
- unordered-containers
- mtl
- hashable

library:
  source-dirs: src

executables:
  ghidra-lifter-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ghidra-lifter

tests:
  ghidra-lifter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ghidra-lifter
